name: myenv
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas=1.3.5
  - numpy=1.22.4
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - xgboost=1.5.2
  - flask=2.2.2
  - werkzeug=2.0.3
  - mlflow=1.23.1
  - joblib=1.1.0
  - pyyaml=6.0
  - optuna=2.10.0
  - pip:
      - gunicorn