data:
  raw_path: "data/raw/housing.csv"
  processed_train_path: "data/processed/train.csv"
  processed_test_path: "data/processed/test.csv"

preprocessing:
  test_size: 0.2
  random_state: 42
  target_column: "price"
  numerical_features: ["sqft", "bedrooms", "bathrooms"]
  categorical_features: ["location", "house_type"]

model:
  type: "RandomForest"
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42
