data:
  raw_path: "data/raw/housing.csv"
  processed_path: "data/processed"
training:
  test_size: 0.2
  random_state: 42
  param_dist: {}
model:
  path: "artifacts/optimized_xgboost_model.pkl"
  scaler_path: "artifacts/scaler.pkl"
  label_encoders_path: "artifacts/label_encoders.pkl"